# Generated by Django 5.2.5 on 2025-08-22 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('expectation', 'Expectation'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='expectation', max_length=30)),
                ('parcipiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_meeting', to=settings.AUTH_USER_MODEL)),
                ('parcipiants', models.ManyToManyField(related_name='parcipiant_meeting', through='timetable.MeetingPatient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meetingpatient',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.meetings'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingpatient',
            unique_together={('meeting', 'parcipiant')},
        ),
    ]
