# Generated by Django 5.2.5 on 2025-08-22 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingpatient',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='meetingpatient',
            constraint=models.UniqueConstraint(fields=('meeting', 'parcipiant'), name='unique_meeting_participant'),
        ),
    ]
