# Generated by Django 5.2.5 on 2025-08-22 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_meetingpatient_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meetingpatient',
            name='unique_meeting_participant',
        ),
        migrations.AlterUniqueTogether(
            name='meetingpatient',
            unique_together={('meeting', 'parcipiant')},
        ),
    ]
