# Generated by Django 5.2.5 on 2025-08-25 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_remove_meetingpatient_unique_meeting_participant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingpatient',
            old_name='parcipiant',
            new_name='participant',
        ),
        migrations.AlterUniqueTogether(
            name='meetingpatient',
            unique_together={('meeting', 'participant')},
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='parcipiants',
        ),
        migrations.AddField(
            model_name='meetings',
            name='participants',
            field=models.ManyToManyField(related_name='participant_meeting', through='timetable.MeetingPatient', to=settings.AUTH_USER_MODEL),
        ),
    ]
