# Generated by Django 5.2.5 on 2025-08-25 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_rename_parcipiant_meetingpatient_participant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingPatient',
            new_name='MeetingParticipant',
        ),
    ]
