# Generated by Django 5.2.5 on 2025-08-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_patient_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('expectation', 'Expectation'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='expectation', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.doctor')),
                ('patients_status', models.ManyToManyField(through='timetable.MeetingPatient', to='account.patient')),
            ],
        ),
        migrations.AddField(
            model_name='meetingpatient',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.meetings'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingpatient',
            unique_together={('meeting', 'patient')},
        ),
    ]
