# Generated by Django 5.2.5 on 2025-08-20 05:42

import django.db.models.deletion
from django.db import migrations, models


def move_doctor_to_host(apps, schema_editor):
    Meetings = apps.get_model("timetable", "Meetings")
    Doctors = apps.get_model("account", "Doctor")

    # migrate old MeetingPatient rows into MeetingParticipants
    for meeting in Meetings.objects.all():
        doctor = Doctors.objects.get(id=meeting.doctor_id)
        meeting.host_id = doctor.user_id
        meeting.save()


def move_patient_to_user(apps, schema_editor):
    MeetingPatient = apps.get_model("timetable", "MeetingPatient")
    Patients = apps.get_model("account", "Patient")

    # migrate old MeetingPatient rows into MeetingPatient
    for participant in MeetingPatient.objects.all():
        patient = Patients.objects.get(id=participant.patient_id)
        participant.participant_id = patient.user_id
        participant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        # doctor to host
        migrations.AddField(
            model_name='meetings',
            name='host',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='host_meeting',
                to='account.user',
                null=True
            ),
        ),
        migrations.RunPython(move_doctor_to_host),
        migrations.RemoveField('meetings', 'doctor'),
        migrations.AlterField(
            model_name='meetings',
            name='host',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='host_meeting',
                to='account.user',
            )
        ),

        # Patient -> Participant
        migrations.AddField(
            model_name='MeetingPatient',
            name='participant',
            field=models.ForeignKey(
                to='account.user',
                related_name='meeting_participants',
                on_delete=models.CASCADE,
                null=True,
            ),
        ),
        migrations.RunPython(move_patient_to_user),
        migrations.AlterField(
            model_name='MeetingPatient',
            name='participant',
            field=models.ForeignKey(
                to='account.user',
                related_name='meeting_participants',
                on_delete=django.db.models.deletion.CASCADE,
            )
        ),

        migrations.AlterUniqueTogether(
            name='MeetingPatient',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='MeetingPatient',
            constraint=models.UniqueConstraint(
                fields=('meeting', 'participant'),
                name='unique_meeting_participant',
            ),
        ),

        migrations.RenameModel(
            "MeetingPatient",
            "MeetingParticipants"
        ),
    ]
