# Generated by Django 5.2.5 on 2025-08-20 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20250820_0542'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipants',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='patients_status',
        ),
        migrations.AddField(
            model_name='meetings',
            name='participants',
            field=models.ManyToManyField(
                related_name='meeting_participants',
                through='timetable.MeetingParticipants',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='meetingparticipants',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
